### ISSUE TITLE
【翻译认领】避免翻译冲突，来此打卡

### ISSUE THREAD

**Issue by ZhangHanDong** [RustcRustc/rustc-dev-guide-zh#1]
翻译交付流程：

1. 认领文章
2. 发 PR
3. 审校 PR
4. 合并

大家好，为了避免翻译冲突，创建该issues。

大家翻译哪个章节，请在该issues下面打卡记录。

认领评论形式：

> `张三-charpter/section/xxx-20210205`，

对应 ：

>  `姓名-章节文件path-交付时间`

如果你想发一个自己专属的「认领issue」也没问题，可以给该`issue`打上「已认领」标签。开一个独立的`issue`好处是可以有一个专属的地方讨论你翻译章节内容里的各种问题。

**Comment by PsiACE** [comment]
PsiACE-appendix/glossary.md-20210203

**Warning:** 
- ~need more time, postponed to 20210205~
- i'm so busy, may need to postpone it to 20210212. sorry, but it's worth more time and effort.

**Comment by ZhangHanDong** [comment]
ZhangHanDong-src/mir/index.md-20210215

**Comment by QuarticCat** [comment]
QuarticCat-src/part-3-intro.md-20210203
QuarticCat-src/cli.md-20210203
QuarticCat-src/rustc-driver.md-20210203
QuarticCat-src/rustc-driver-interacting-with-the-ast.md-20210203
QuarticCat-src/rustc-driver-getting-diagnostics.md-20210203

**Comment by longfangsong** [comment]
longfangsong-src/building/how-to-build-and-run.md-pr已发
longfangsong-src/compiler-src.md-pr已发
longfangsong-src/query.md-pr已发
longfangsong-src/hir.md-pr已发
longfangsong-src/lowering.md-pr已发
longfangsong-src/mir/construction.md-pr已发
longfangsong-src/rustdoc.md-pr已发
longfangsong-src/rustdoc-internals.md-pr已发
longfangsong-src/mir/visitor.md-pr已发
longfangsong-src/src/compiler-debugging.md-20210405
longfangsong-src/mir/passes.md-20210410
longfangsong-src/ty.md-20210415
longfangsong-src/generics.md-20210420

**Comment by Hyiker** [comment]
Hyiker-src/part-2-intro.md-20210201
Hyiker-src/overview.md-20210225

**Comment by JialuGong** [comment]
- [x] JialuGong-src/tests/adding.md-20210210
- [ ] ~~JialuGong-src/tests/intro.md-20210301~~
- [ ] ~~JialuGong-src/tests/running.md-20210301~~
- [x] JialuGong-src/tests/intro.md-20210305
- [x] JialuGong-src/tests/running.md-20210305
I've not finished it on time for that I'm too busy recently<(=┳＿┳=)>.And I will finish them in next the 4 days.

**Comment by ZhangHanDong** [comment]
> QuarticCat-src/part-3-intro.md-20210203
> QuarticCat-src/cli.md-20210203
> QuarticCat-src/rustc-driver.md-20210203
> QuarticCat-src/rustc-driver-interacting-with-the-ast.md-20210203
> QuarticCat-src/rustc-driver-getting-diagnostics.md-20210203

已Merge

**Comment by quanee** [comment]
- [x] quanee-[src/memory.md](https://github.com/RustcRustc/rustc-dev-guide-zh/blob/main/src/memory.md)
- [x] quanee-[src/serialization.md](https://github.com/RustcRustc/rustc-dev-guide-zh/blob/main/src/serialization.md)
- [x] quanee-[src/parallel-rustc.md](https://github.com/RustcRustc/rustc-dev-guide-zh/blob/main/src/parallel-rustc.md)
- [x] quanee-[src/panic-implementation.md](https://github.com/rust-lang/rustc-dev-guide/blob/master/src/panic-implementation.md)
- [x] quanee-[src/type-checking.md](https://github.com/rust-lang/rustc-dev-guide/blob/master/src/backend/type-checking.md)
- [ ] quanee-[src/backend/lowering-mir.md](https://github.com/rust-lang/rustc-dev-guide/blob/master/src/backend/lowering-mir.md)
- [ ] quanee-[src/backend/codegen.md](https://github.com/rust-lang/rustc-dev-guide/blob/master/src/backend/codegen.md)

**Comment by iamazy** [comment]
- [x] [iamazy-src/closure.md-20210228](https://github.com/rust-lang/rustc-dev-guide/blob/master/src/closure.md)

**Comment by WenyXu** [comment]
- [x] WenyXu-src/syntax-intro.md-20210307
- [x] WenyXu-src/the-parser.md-20210307 
- [x] WenyXu-src/macro-expansion.md-20210307 
- [x] WenyXu-src/name-resolution.md-20210321
- [x] WenyXu-src/test-implementation.md-20210321

**Comment by MATRIXKOO** [comment]
- [x] Matrixtang-src/backend/backend-agnostic.md-20210410
- [ ] Matrixtang-src/backend/debugging.md.md-20210417

**Comment by penguin-wwy** [comment]
- [x] penguin_wwy/src/mir/optimizations-20210410(https://github.com/RustcRustc/rustc-dev-guide-zh/pull/25)
- [x] penguin_wwy/src/mir/dataflow-20210410(https://github.com/RustcRustc/rustc-dev-guide-zh/pull/28)
- [ ] penguin_wwy/src/mir/debugging-20210501

**Comment by xiandaoyan** [comment]
xiandaoyan-src/mir/passes.md-2023-01-09

这个页面我在学习的过程中已经翻译了，希望提交上去，后续有新的页面我翻译了再申请，请问可以吗？

**Comment by ZhangHanDong** [comment]
@xiandaoyan  暂时不要翻译了，规范打算重新调整，预计3月份以后再翻译吧

**Comment by MATRIXKOO** [comment]
> @xiandaoyan  暂时不要翻译了，规范打算重新调整，预计3月份以后再翻译吧

之后重启翻译项目的时候可以在这个issue下面 提醒一下吗？🙏
